# Site settings
title: PlayMusic
subtitle: by Brett Stevenson
email: BStevensonDev@gmail.com
description: A Rainmeter skin that allows Google Play Music users <br/>to access their music tastefully on their desktop
baseurl: "/PlayMusic" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Brett Stevenson
country: United States of America
repo: https://github.com/tterb/PlayMusic
issue: https://github.com/tterb/PlayMusic/issues/new

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Social settings
github_url: https://github.com/tterb/PlayMusic
deviantart_url: http://bstevenson.deviantart.com/art/PlayMusic-620128929
dribbble_url: https://dribbble.com/tterb
linkedin_url: https://www.linkedin.com/in/brett-stevenson-0a035a72/
twitter_url: https://twitter.com/BStevensonDev
# 500px_url:
# facebook_url:
# gitlab_url:
# googleplus_url:
# instagram_url:
# pinterest_url:
# slack_url:

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
include: ['_pages','_projects','.htaccess']
exclude: ['.gitignore', 'README.md', 'Gulpfile.js', 'package.json', 'package-lock.json', 'node_modules', 'jspm_packages']

defaults:
  - scope:
      path: _pages
    values:
      layout: page
